export const DATAPETS = [
  {
    id: 1,
    name: "Abraham",
    lastname: "Leonard",
    age: "24",
    pathimage: "/images/pets/dog-01.jpg",
    position: "Accounting Officer",
    gender: "Male",
  },
  {
    id: 2,
    name: "Burrell",
    lastname: "Merton",
    age: "23",
    pathimage: "/images/pets/cat-01.jpg",
    position: "Technical Support",
    gender: "Female",
  },
  {
    id: 3,
    name: "Clinton",
    lastname: "Evans",
    age: "26",
    pathimage: "/images/pets/dog-02.jpg",
    position: "Service Technician",
    gender: "Male",
  },
  {
    id: 4,
    name: "Donald",
    lastname: "Willis ",
    age: "25",
    pathimage: "/images/pets/cat-02.jpg",
    position: "Industrial Engineer",
    gender: "Male",
  },
  {
    id: 5,
    name: "Evanson",
    lastname: "Williams",
    age: "18",
    pathimage: "/images/pets/dog-03.jpg",
    position: "Design Engineer",
    gender: "Male",
  },
  {
    id: 6,
    name: "Johnson",
    lastname: "Walsh",
    age: "31",
    pathimage: "/images/pets/cat-03.jpg",
    position: "Messenger",
    gender: "Female",
  },
  {
    id: 7,
    name: "Hurricane",
    lastname: "Taylor",
    age: "30",
    pathimage: "/images/pets/dog-04.jpg",
    position: "Driver",
    gender: "Male",
  },
  {
    id: 8,
    name: "Kellogg",
    lastname: "Smith",
    age: "21",
    pathimage: "/images/pets/cat-04.jpg",
    position: "Receptionist",
    gender: "Female",
  },
  {
    id: 9,
    name: "Gonzalez",
    lastname: "Simpsons",
    age: "21",
    pathimage: "/images/pets/dog-05.jpg",
    position: "Office Assistant",
    gender: "Female",
  },
  {
    id: 10,
    name: "Harris",
    lastname: "Pemberton",
    age: "20",
    pathimage: "/images/pets/cat-05.jpg",
    position: "Pilot",
    gender: "Female",
  },
];
